name: Flutter-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
defaults:
  run:
    working-directory: stopstalk_app

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1.3.2
    - run: cp .env.example .env
    - name: Install Deps
      run: flutter pub get
    - name: Build android
      run: flutter build apk