name: Release
on:
  push:
    tags:
      - "v*"
defaults:
  run:
    working-directory: stopstalk_app

jobs:
  apk:
    name: Release APK
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Generate Debug APK
        run: |
          cp .env.example .env
          flutter pub get
          flutter build apk --split-per-abi
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "stopstalk_app/build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.TOKEN }}
